### ISSUE TITLE
Render-time options are not consistent

### ISSUE THREAD

**Issue by wwboynton** [peter-murach/tty-table#4]
It seems like rendering a table changes some of the properties of the table itself based on the context of the render, rather than simply changing the properties for that render output only.

For instance, if I instantiate a table too wide for the terminal and it defaults to vertical display, I can add a render-time line to make note of this and force separation between each line. However, it only works the first time I render it. If I instantiate a table and then run the same render twice in a row, it will produce different results. 

        1.9.3-p392 :088 > table = TTY::Table.new({rows: [['deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh','swaaaaaaaaaaaaag','deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh','deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh','deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh'], ['next','row',3,4,5]], header:['derp','deh',3,4,5]})
         => #<TTY::Table header=#<TTY::Table::Header attributes=[#<TTY::Table::Field value="derp" name=nil width=4 colspan=1 rowspan=1 align=nil>, #<TTY::Table::Field value="deh" name=nil width=3 colspan=1 rowspan=1 align=nil>, #<TTY::Table::Field value=3 name=nil width=1 colspan=1 rowspan=1 align=nil>, #<TTY::Table::Field value=4 name=nil width=1 colspan=1 rowspan=1 align=nil>, #<TTY::Table::Field value=5 name=nil width=1 colspan=1 rowspan=1 align=nil>]> rows=[#<TTY::Table::Row fields=["deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh", "swaaaaaaaaaaaaag", "deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh", "deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh", "deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh"]>, #<TTY::Table::Row fields=["next", "row", 3, 4, 5]>] orientation=#<TTY::Table::Orientation::Horizontal:0x007f87ca912db0 @name=:horizontal> original_rows=nil original_columns=nil>
        1.9.3-p392 :089 > puts table.render(:unicode) { |renderer| renderer.border.separator = :each_row unless table.orientation.vertical?; puts table.orientation.vertical? }false
        The table size exceeds the currently set width.To avoid error either. Defaulting to vertical orientation.
        ┌────┬────────────────────────────────────────────────────────────────────────┐
        │derp│deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh│
        ├────┼────────────────────────────────────────────────────────────────────────┤
        │deh │swaaaaaaaaaaaaag                                                        │
        ├────┼────────────────────────────────────────────────────────────────────────┤
        │3   │deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh│
        ├────┼────────────────────────────────────────────────────────────────────────┤
        │4   │deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh│
        ├────┼────────────────────────────────────────────────────────────────────────┤
        │5   │deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh│
        ├────┼────────────────────────────────────────────────────────────────────────┤
        │derp│next                                                                    │
        ├────┼────────────────────────────────────────────────────────────────────────┤
        │deh │row                                                                     │
        ├────┼────────────────────────────────────────────────────────────────────────┤
        │3   │3                                                                       │
        ├────┼────────────────────────────────────────────────────────────────────────┤
        │4   │4                                                                       │
        ├────┼────────────────────────────────────────────────────────────────────────┤
        │5   │5                                                                       │
        └────┴────────────────────────────────────────────────────────────────────────┘
         => nil
        1.9.3-p392 :090 > puts table.render(:unicode) { |renderer| renderer.border.separator = :each_row unless table.orientation.vertical?; puts table.orientation.vertical? }
        true
        ┌────┬────────────────────────────────────────────────────────────────────────┐
        │derp│deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh│
        │deh │swaaaaaaaaaaaaag                                                        │
        │3   │deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh│
        │4   │deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh│
        │5   │deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeh│
        │derp│next                                                                    │
        │deh │row                                                                     │
        │3   │3                                                                       │
        │4   │4                                                                       │
        │5   │5                                                                       │
        └────┴────────────────────────────────────────────────────────────────────────┘
         => nil

**Comment by peter-murach** [comment]
Understand

**Comment by peter-murach** [comment]
This has been fixed in master.
